gMonHatchSpriteGroup0_Pals:: @ 0x0
	.incbin "graphics/mon_hatch_sprites/wurmple_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/lotad_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/seedot_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/ralts_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/surskit_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/shroomish_hatch.gbapal"

gMonHatchSpriteGroup1_Pals:: @ 0x0
	.incbin "graphics/mon_hatch_sprites/whismur_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/azurill_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/skitty_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/zubat_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/aron_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/plusle_hatch.gbapal"

gMonHatchSpriteGroup2_Pals:: @ 0x0
	.incbin "graphics/mon_hatch_sprites/minun_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/oddish_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/gulpin_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/spoink_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/sandshrew_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/spinda_hatch.gbapal"

gMonHatchSpriteGroup3_Pals:: @ 0x0
	.incbin "graphics/mon_hatch_sprites/trapinch_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/igglybuff_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/shuppet_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/chimecho_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/pichu_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/wynaut_hatch.gbapal"

gMonHatchSpriteGroup4_Pals:: @ 0x0
	.incbin "graphics/mon_hatch_sprites/natu_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/phanpy_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/snorunt_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/spheal_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/corsola_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/chinchou_hatch.gbapal"

gMonHatchSpriteGroup5_Pals:: @ 0x0
	.incbin "graphics/mon_hatch_sprites/horsea_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/bagon_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/pichu_2_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/cleffa_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/elekid_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/magby_hatch.gbapal"

gMonHatchSpriteGroup6_Pals:: @ 0x0
	.incbin "graphics/mon_hatch_sprites/smoochum_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/swinub_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/togepi_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/tyrogue_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/bonsly_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/budew_hatch.gbapal"

gMonHatchSpriteGroup7_Pals:: @ 0x0
	.incbin "graphics/mon_hatch_sprites/chingling_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/happiny_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/manaphy_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/mantyke_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/mimejr_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/munchlax_hatch.gbapal"

gMonHatchSpriteGroup8_Pals:: @ 0x0
	.incbin "graphics/mon_hatch_sprites/riolu_hatch.gbapal"
