"""Pack the supplied indexed PNGs as lossless RLE for the pause encounters view."""

import argparse
import hashlib
from pathlib import Path
import struct
import zlib

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / 'src/data/encounters_assets.h'


def read_png(path, indexed=False):
    data = path.read_bytes()
    assert data[:8] == b'\x89PNG\r\n\x1a\n'
    w, h, depth, mode, compression, filtering, interlace = struct.unpack('>IIBBBBB', data[16:29])
    assert depth in (4, 8) and mode == 3 and compression == filtering == interlace == 0, path
    pos, compressed, palette = 8, b'', []
    while pos < len(data):
        size = struct.unpack('>I', data[pos:pos + 4])[0]
        kind, chunk = data[pos + 4:pos + 8], data[pos + 8:pos + 8 + size]
        if kind == b'IDAT':
            compressed += chunk
        if kind == b'PLTE':
            palette = [tuple(chunk[i:i + 3]) for i in range(0, size, 3)]
        pos += size + 12
    raw = zlib.decompress(compressed)
    stride = (w * depth + 7) // 8
    assert len(raw) == h * (stride + 1)
    previous, pixels = [0] * stride, []
    for y in range(h):
        kind = raw[y * (stride + 1)]
        row = list(raw[y * (stride + 1) + 1:(y + 1) * (stride + 1)])
        for x in range(stride):
            a, b, c = row[x - 1] if x else 0, previous[x], previous[x - 1] if x else 0
            p = a + b - c
            paeth = min((a, b, c), key=lambda v: abs(p - v))
            row[x] = (row[x] + (0, a, b, (a + b) // 2, paeth)[kind]) & 255
        indices = row if depth == 8 else [v for byte in row for v in (byte >> 4, byte & 15)][:w]
        pixels.extend(indices)
        previous = row
    if indexed:
        return w, h, pixels, palette
    return w, h, [palette[index] for index in pixels]


def generate():
    colors = [(0, 255, 0), (0, 0, 0), (255, 255, 255)]
    arrays = []
    for name, filename, size in (
        ('Background', 'Encounters.png', (240, 160)),
        ('Frames', 'Encounters_Frames.png', (54, 80)),
        ('Buttons', 'Encounters_Buttons.png', (16, 32)),
    ):
        path = ROOT / 'graphics/options' / filename
        w, h, pixels = read_png(path)
        assert (w, h) == size, path
        indices = []
        for color in pixels:
            if color not in colors:
                colors.append(color)
            indices.append(colors.index(color))
        runs = []
        for index in indices:
            if runs and runs[-1] & 255 == index and runs[-1] >> 8 < 255:
                runs[-1] += 256
            else:
                runs.append(256 | index)
        arrays.append(f'/* {filename}: {hashlib.sha256(path.read_bytes()).hexdigest()} */\n'
                      + f'static const u16 sEncounters{name}[] = {{\n'
                      + '\n'.join('    ' + ', '.join(f'0x{v:04X}' for v in runs[i:i + 12]) + ','
                                  for i in range(0, len(runs), 12)) + '\n};\n')
    assert len(colors) <= 32, 'UI must leave palette entries 32..175 for portraits'
    colors += [(0, 0, 0)] * (32 - len(colors))
    palette = [(r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10) for r, g, b in colors]
    return ('/* Generated by tools/scripts/generate_encounters_assets.py. */\n'
            + 'static const u16 sEncountersPalette[32] = {\n    '
            + ', '.join(f'0x{v:04X}' for v in palette) + '\n};\n' + '\n'.join(arrays))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = generate()
    if args.check:
        assert OUTPUT.read_text() == output, 'Regenerate encounters assets'
    else:
        OUTPUT.write_text(output, encoding='ascii')
    print('PASS: encounters PNG dimensions, shared palette and generated assets')
