#ifndef GUARD_CONSTANTS_LEGENDARY_ENCOUNTERS_H
#define GUARD_CONSTANTS_LEGENDARY_ENCOUNTERS_H

#define RANDOM_LEGENDARY_ROAMER_COUNT 2
#define RANDOM_LEGENDARY_SPECIAL_COUNT 2

enum LegendaryRoamerGroup
{
    LEGENDARY_ROAM_BIRDS,
    LEGENDARY_ROAM_BEASTS,
    LEGENDARY_ROAM_MESPRIT,
    LEGENDARY_ROAM_CRESSELIA,
    LEGENDARY_ROAM_GROUP_COUNT
};

enum LegendarySpecialGroup
{
    LEGENDARY_SPECIAL_MEW,
    LEGENDARY_SPECIAL_MEWTWO,
    LEGENDARY_SPECIAL_HO_OH,
    LEGENDARY_SPECIAL_LUGIA,
    LEGENDARY_SPECIAL_CELEBI,
    LEGENDARY_SPECIAL_DEOXYS,
    LEGENDARY_SPECIAL_LAKE_PAIR,
    LEGENDARY_SPECIAL_DIALGA,
    LEGENDARY_SPECIAL_PALKIA,
    LEGENDARY_SPECIAL_HEATRAN,
    LEGENDARY_SPECIAL_REGIGIGAS,
    LEGENDARY_SPECIAL_GIRATINA,
    LEGENDARY_SPECIAL_PHIONE,
    LEGENDARY_SPECIAL_DARKRAI,
    LEGENDARY_SPECIAL_SHAYMIN,
    LEGENDARY_SPECIAL_ARCEUS,
    LEGENDARY_SPECIAL_GROUP_COUNT
};

#endif
